services:
  backend:
    container_name: backendcontainer
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - "./logs:/logs"
      - "./maps:/maps"
    depends_on:
      - postgres
    networks:
      - backendnet

  postgres:
    image: postgres:16.3
    container_name: postgrescontainer
    restart: unless-stopped
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    expose:
      - "5432"
    networks:
      - backendnet

networks:
  backendnet:
    driver: bridge

volumes:
  postgres-data:
    driver: local
